const api=require('../../utils/request');const chart=require('../../utils/canvasChart')
Page({
  data:{loading:true,aiLoading:false,error:'',r:null,ai:null,scoreText:'--',displayAvg:{sleep:'--',exercise:'--',water:'--',protein:'--'},coverageText:'',qualityText:'',compare:[],metric:'exercise_min',metricName:'运动',metricUnit:' min',metricDecimals:0,activeValue:'触摸图表查看单日数据',tabs:[{k:'exercise_min',n:'运动',u:' min',d:0},{k:'water_ml',n:'饮水',u:' ml',d:0},{k:'sleep_hours',n:'睡眠',u:' h',d:1},{k:'calories',n:'热量',u:' kcal',d:0}]},
  onShow(){this.load()},onUnload(){this._charts=null},
  buildMeta(r){const c=r.coverage||{},q=r.data_quality||{},cp=r.completion||{};const quality={high:'较高',medium:'中等',low:'较低'}[q.confidence]||'未知';const coverageText=`打卡 ${c.checkin_days||0}/7 · 饮食 ${c.diet_days||0}/7 · 运动 ${c.exercise_days||0}/7`;const defs=[['sleep_hours','睡眠','h'],['exercise_min','运动',' min'],['water_ml','饮水',' ml'],['steps','步数',' 步']];const compare=defs.map(x=>{const v=r.changes&&r.changes[x[0]];if(v===null||v===undefined)return null;return {name:x[1],text:`${v>0?'+':''}${v}${x[2]}`,up:v>0,flat:v===0}}).filter(Boolean);const observed=k=>cp[k]&&cp[k].observed_days>0;const displayAvg={sleep:observed('sleep_hours')?r.averages.sleep_hours:'--',exercise:observed('exercise_min')?r.averages.exercise_min:'--',water:observed('water_ml')?r.averages.water_ml:'--',protein:observed('protein')?r.averages.protein:'--'};this.setData({scoreText:r.score===null||r.score===undefined?'--':String(r.score),displayAvg,coverageText,qualityText:`数据完整程度：${quality}`,compare})},
  async load(){this.setData({loading:true,error:''});try{const r=await api.get('/insights/weekly-report');this.setData({r});this.buildMeta(r);setTimeout(()=>this.renderChart(),80);this.loadAI()}catch(e){this.setData({error:e.message||'周报暂时生成不了'})}finally{this.setData({loading:false})}},
  retry(){this.load()},
  async loadAI(){if(this.data.aiLoading)return;this.setData({aiLoading:true});try{const ai=await api.postLong('/insights/weekly-report/ai-summary',{});this.setData({ai})}catch(e){console.warn(e)}finally{this.setData({aiLoading:false})}},
  pickMetric(e){const t=this.data.tabs[Number(e.currentTarget.dataset.i)];this.setData({metric:t.k,metricName:t.n,metricUnit:t.u,metricDecimals:t.d,activeValue:'触摸图表查看单日数据'});setTimeout(()=>this.renderChart(),30)},
  renderChart(){if(!this.data.r)return;const data=(this.data.r.days||[]).map(x=>({label:x.label,value:x[this.data.metric]==null?null:Number(x[this.data.metric])}));const options={data,suffix:this.data.metricUnit,decimals:this.data.metricDecimals,tickFormatter:v=>this.data.metric==='sleep_hours'?Number(v).toFixed(1):v>=1000?(v/1000).toFixed(1)+'k':Math.round(v)};if(this._charts&&this._charts.week)chart.draw(this,'week',options);else chart.init(this,'#weekCanvas','week',options)},
  chartTouch(e){const i=chart.touch(this,'week',e);if(i<0)return;const d=this.data.r.days[i],v=Number(d[this.data.metric])||0;this.setData({activeValue:`${d.label} · ${this.data.metricName} ${v.toFixed(this.data.metricDecimals)}${this.data.metricUnit}`})}
})
