const api=require('../../utils/request');const chart=require('../../utils/canvasChart')
Page({
  data:{loading:true,error:'',days:[],displayDays:[],avg:{water:'--',sleep:'--',exercise:'--',steps:'--'},metric:'water_ml',metricName:'饮水',metricUnit:' ml',metricDecimals:0,activeValue:'触摸图表查看每日数据',tabs:[{k:'water_ml',n:'饮水',u:' ml',d:0},{k:'sleep_hours',n:'睡眠',u:' h',d:1},{k:'exercise_min',n:'运动',u:' min',d:0},{k:'steps',n:'步数',u:' 步',d:0}]},
  onLoad(){this.load()},onUnload(){this._charts=null},
  avgOf(d,k,decimals=0){const v=d.filter(x=>x[k]!==null&&x[k]!==undefined).map(x=>Number(x[k]));if(!v.length)return '--';const n=v.reduce((a,b)=>a+b,0)/v.length;return decimals? n.toFixed(decimals):Math.round(n)},
  async load(){this.setData({loading:true,error:''});try{let r=await api.get('/health/trends/7d');let d=r.days||[];let displayDays=d.map(x=>Object.assign({},x,{water_text:x.water_ml==null?'未记录':x.water_ml,sleep_text:x.sleep_hours==null?'未记录':x.sleep_hours+'h',exercise_text:x.exercise_min==null?'未记录':x.exercise_min+'m',steps_text:x.steps==null?'未记录':x.steps}));this.setData({days:d,displayDays,avg:{water:this.avgOf(d,'water_ml'),sleep:this.avgOf(d,'sleep_hours',1),exercise:this.avgOf(d,'exercise_min'),steps:this.avgOf(d,'steps')}});setTimeout(()=>this.renderChart(),80)}catch(e){this.setData({error:e.message||'趋势数据加载失败'})}finally{this.setData({loading:false})}},
  retry(){this.load()},
  pickMetric(e){const t=this.data.tabs[Number(e.currentTarget.dataset.i)];this.setData({metric:t.k,metricName:t.n,metricUnit:t.u,metricDecimals:t.d,activeValue:'触摸图表查看每日数据'});setTimeout(()=>this.renderChart(),30)},
  renderChart(){const data=this.data.days.map(x=>({label:x.label,value:x[this.data.metric]==null?null:Number(x[this.data.metric])}));const options={data,suffix:this.data.metricUnit,decimals:this.data.metricDecimals,tickFormatter:v=>this.data.metric==='steps'?(v>=1000?(v/1000).toFixed(v>=10000?0:1)+'k':Math.round(v)):this.data.metric==='water_ml'?(v>=1000?(v/1000).toFixed(1)+'k':Math.round(v)):this.data.metric==='sleep_hours'?Number(v).toFixed(1):Math.round(v)};if(this._charts&&this._charts.trend)chart.draw(this,'trend',options);else chart.init(this,'#trendCanvas','trend',options)},
  chartTouch(e){const i=chart.touch(this,'trend',e);if(i<0)return;const d=this.data.days[i];const value=Number(d[this.data.metric]);this.setData({activeValue:`${d.label} · ${this.data.metricName} ${value.toFixed(this.data.metricDecimals)}${this.data.metricUnit}`})}
})
