"""Probe whether the configured DeepSeek vision model actually works.

The API key is read from DEEPSEEK_API_KEY in ai-worker/.env (git-ignored);
never hard-code a key here.
"""
import base64
import io
import os
import sys

import dotenv
import httpx
from PIL import Image

dotenv.load_dotenv()
KEY = os.environ.get("DEEPSEEK_API_KEY") or ""
if not KEY:
    print("DEEPSEEK_API_KEY not set in ai-worker/.env", file=sys.stderr)
    raise SystemExit(2)
BASE = os.environ.get("DEEPSEEK_BASE_URL") or "https://api.deepseek.com/v1"

# A valid, normal-size JPEG (red apple-ish block) generated by PIL.
buf = io.BytesIO()
img = Image.new("RGB", (224, 224), (200, 40, 40))
img.save(buf, format="JPEG", quality=90)
data_url = "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()

for model in ("deepseek-flash", "deepseek-chat"):
    payload = {
        "model": model,
        "messages": [
            {"role": "user", "content": [
                {"type": "text", "text": "what is this?"},
                {"type": "image_url", "image_url": {"url": data_url}},
            ]}
        ],
        "max_tokens": 64,
    }
    try:
        r = httpx.post(BASE + "/chat/completions",
                       headers={"Authorization": f"Bearer {KEY}"},
                       json=payload, timeout=60)
        print(f"model={model:15s} status={r.status_code}")
        if r.is_success:
            print("  ->", r.json()["choices"][0]["message"]["content"][:120])
        else:
            print("  ->", r.text[:300])
    except Exception as exc:
        print(f"model={model} error {exc}")
