<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { compilePolicy, confirmUserAction, createPolicyEpisodeProposal, readCurrentPolicyEpisode, readPolicyCandidates } from '../services/api'
import { useAuthStore } from '../stores/auth'

const router = useRouter(); const auth = useAuthStore()
const candidate = ref<Record<string, any> | null>(null); const minutes = ref(15); const compiled = ref<Record<string, any> | null>(null); const proposal = ref<Record<string, any> | null>(null)
const loading = ref(true); const busy = ref(false); const error = ref('')
async function load() { loading.value = true; error.value = ''; try { candidate.value = await readPolicyCandidates(auth.accessToken); const current = await readCurrentPolicyEpisode(auth.accessToken); if (current.episode) { await router.replace({ path: '/policy/episode', query: { id: current.episode.episode_id } }); return } } catch (cause) { error.value = cause instanceof Error ? cause.message : '协议条件暂时无法读取' } finally { loading.value = false } }
async function compile() { if (!candidate.value?.can_compile || !candidate.value?.can_propose || busy.value) return; busy.value = true; error.value = ''; try { compiled.value = await compilePolicy(auth.accessToken, minutes.value, `policy-compile-${crypto.randomUUID()}`) } catch (cause) { error.value = cause instanceof Error ? cause.message : '协议没有生成' } finally { busy.value = false } }
async function start() { if (!compiled.value || busy.value) return; if (!window.confirm(`确认开始 7 天个人周期？\n\n每次训练 ${minutes.value} 分钟；记录是否完成和主观训练负担。基线与周期内各至少需要 5 条观察。结果不证明因果。`)) return; busy.value = true; error.value = ''; try { proposal.value = await createPolicyEpisodeProposal(auth.accessToken, compiled.value.strategy_unit_id); if (!window.confirm(`${proposal.value.title || '确认开始个人周期'}\n\n${proposal.value.summary || '只有再次确认后，周期才会开始。'}`)) return; await confirmUserAction(auth.accessToken, proposal.value.proposal_id, proposal.value.version || 1); const current = await readCurrentPolicyEpisode(auth.accessToken); if (!current.episode) throw new Error('申请已处理，但暂时读不到当前周期，请返回刷新。'); await router.replace({ path: '/policy/episode', query: { id: current.episode.episode_id } }) } catch (cause) { error.value = cause instanceof Error ? cause.message : '周期没有开始' } finally { busy.value = false } }
onMounted(() => void load())
</script>

<template>
  <section class="page protocol-page"><header class="page-heading"><button class="back-button" aria-label="返回" @click="router.back()">‹</button><div><p class="eyebrow">开始前确认</p><h1>设置个人周期</h1></div></header><div v-if="loading" class="card-surface message">正在检查当前设置…</div><section v-else class="card-surface protocol-card"><h2>选择每次训练时长</h2><p>开始后将按同一标准记录 7 天，方便之后回顾。</p><div class="choice-grid"><button v-for="value in [10,15,20]" :key="value" :class="{ selected: minutes === value }" :disabled="!!compiled" @click="minutes=value">{{ value }} 分钟</button></div><div class="protocol-row"><span>主要观察</span><b>主观训练负担自评（0–10）</b></div><div class="protocol-row"><span>周期长度</span><b>7 天</b></div><div class="protocol-row"><span>建议记录次数</span><b>开始前和周期内各至少 5 次</b></div><p class="note">自评反映个人感受，不代表动作质量或健康指标。记录不足时会如实提示。</p><ul><li v-for="reason in candidate?.reasons || []" :key="reason">{{ reason }}</li></ul><p v-if="compiled" class="compiled">已准备好 · {{ compiled.protocol?.summary || '' }}</p><p v-if="error" class="error">{{ error }}</p><button v-if="!compiled" class="primary" :disabled="busy || !candidate?.can_compile || !candidate?.can_propose" @click="compile">{{ busy ? '正在准备…' : '确认本周期规则' }}</button><button v-if="compiled" class="primary" :disabled="busy" @click="start">{{ busy ? '正在处理…' : '确认并开始 7 天周期' }}</button><button v-if="!candidate?.can_compile || !candidate?.can_propose" class="secondary" @click="router.push('/settings/capabilities')">查看功能设置</button></section></section>
</template>

<style scoped>
.protocol-page{padding:9px 0 24px}.page-heading{display:flex;align-items:center;gap:9px;margin-bottom:13px}.page-heading h1{margin:3px 0 0;font-size:22px}.back-button{width:35px;height:35px;border:0;border-radius:50%;background:#fff;font-size:24px}.protocol-card{padding:15px}.protocol-card h2{margin:0 0 7px;font-size:17px}.protocol-card>p{color:#62685f;font-size:10px;line-height:1.55}.choice-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:12px 0}.choice-grid button{min-height:40px;border:1px solid #eeeee6;border-radius:11px;background:#f7f7f2;font-size:11px}.choice-grid button.selected{border-color:#9fb845;background:#e9efd9;color:#506336;font-weight:700}.protocol-row{display:flex;justify-content:space-between;gap:8px;padding:9px 0;border-top:1px solid #eeeee6;font-size:10px}.protocol-row span,.note{color:#737a70}.protocol-row b{font-size:10px;text-align:right}.note{font-size:9px;line-height:1.5}.protocol-card ul{padding-left:17px;color:#7c4d27;font-size:9px;line-height:1.6}.primary,.secondary{width:100%;min-height:40px;margin-top:8px;border:0;border-radius:11px;background:#c4e267;font-size:10px;font-weight:700}.primary:disabled{opacity:.5}.secondary{background:#e9efd9;color:#506336}.error{color:#8f3028}.compiled{padding:9px;border-radius:11px;background:#e9efd9;color:#506336;font-size:10px}.message{padding:14px;color:#737a70;font-size:11px}
</style>
