# -*- coding: utf-8 -*-
"""Generate the three同源 motion catalog artifacts from catalog.yaml.

Single source of truth: motion_catalog/catalog.yaml
Generated artifacts (do NOT edit by hand; re-run this script):
  - backend/app/services/motion/catalog_data.py
  - ai-worker/healthmate_worker/catalog_data.py
  - miniprogram/utils/motionCatalogData.js

Idempotent: running twice produces byte-identical output.
No network / model calls. Pure local file IO.
"""
from __future__ import annotations

import json
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent

BACKEND_DATA = REPO_ROOT / "backend" / "app" / "services" / "motion" / "catalog_data.py"
WORKER_DATA = REPO_ROOT / "ai-worker" / "healthmate_worker" / "catalog_data.py"
MINI_DATA = REPO_ROOT / "miniprogram" / "utils" / "motionCatalogData.js"

HEADER = (
    "# AUTO-GENERATED by motion_catalog/generate.py from catalog.yaml.\n"
    "# DO NOT EDIT BY HAND. Re-run: python motion_catalog/generate.py\n"
)

SIX_LEGACY_IDS = {
    "squat", "pushup", "lunge", "leg_abduction", "arm_abduction", "arm_vw",
}


def load_catalog() -> dict:
    data = yaml.safe_load((HERE / "catalog.yaml").read_text(encoding="utf-8"))
    actions = data["actions"]
    # ---- validation: ids unique, required fields present ----
    seen = set()
    for a in actions:
        aid = a["id"]
        if aid in seen:
            raise ValueError(f"duplicate action id: {aid}")
        seen.add(aid)
        if not a.get("name_zh"):
            raise ValueError(f"{aid}: name_zh must be non-empty")
        if not a.get("aliases"):
            raise ValueError(f"{aid}: aliases must be non-empty")
    # ---- build kinetics label -> canonical id map (first writer wins) ----
    k2id: dict[str, str] = {}
    for a in actions:
        for k in a.get("kinetics_labels") or []:
            label, idx = k["label"], k["class_index"]
            if label in k2id and k2id[label] != a["id"]:
                raise ValueError(
                    f"kinetics label {label!r} maps to both {k2id[label]!r} and {a['id']!r}"
                )
            k2id[label] = a["id"]
    data["_kinetics_to_id"] = k2id
    return data


def normalize_action(a: dict) -> dict:
    """Strip YAML-only helper fields; keep the portable data shape."""
    return {
        "id": a["id"],
        "name_zh": a["name_zh"],
        "aliases": list(a["aliases"]),
        "kinetics_labels": [
            {"label": k["label"], "class_index": k["class_index"]}
            for k in (a.get("kinetics_labels") or [])
        ],
        "kinetics_note": a.get("kinetics_note"),
        "visible_regions": list(a.get("visible_regions") or []),
        "context_cues": list(a.get("context_cues") or []),
        "capabilities": dict(a["capabilities"]),
        "knowledge_keys": list(a.get("knowledge_keys") or []),
    }


def render_py(catalog: dict) -> str:
    actions = [normalize_action(a) for a in catalog["actions"]]
    k2id = catalog["_kinetics_to_id"]
    lines = [
        HEADER,
        f"CATALOG_VERSION = {catalog['catalog_version']!r}",
        f"CAPABILITY_PENDING_NOTE = {catalog['capability_pending_note']!r}",
        "",
        f"ACTIONS = {repr(actions)}",
        "",
        f"KINETICS_TO_ID = {repr(k2id)}",
        "",
    ]
    return "\n".join(lines)


def render_js(catalog: dict) -> str:
    actions = [normalize_action(a) for a in catalog["actions"]]
    k2id = catalog["_kinetics_to_id"]
    out = (
        "// AUTO-GENERATED by motion_catalog/generate.py from catalog.yaml.\n"
        "// DO NOT EDIT BY HAND. Re-run: python motion_catalog/generate.py\n"
        f"const CATALOG_VERSION = {json.dumps(catalog['catalog_version'], ensure_ascii=False)};\n"
        f"const CAPABILITY_PENDING_NOTE = {json.dumps(catalog['capability_pending_note'], ensure_ascii=False)};\n"
        "const ACTIONS = "
        + json.dumps(actions, ensure_ascii=False, indent=2)
        + ";\n"
        "const KINETICS_TO_ID = "
        + json.dumps(k2id, ensure_ascii=False, indent=2)
        + ";\n"
        "module.exports = { CATALOG_VERSION, CAPABILITY_PENDING_NOTE, ACTIONS, KINETICS_TO_ID };\n"
    )
    return out


def main() -> None:
    catalog = load_catalog()
    py = render_py(catalog)
    BACKEND_DATA.write_text(py, encoding="utf-8")
    WORKER_DATA.write_text(py, encoding="utf-8")
    MINI_DATA.write_text(render_js(catalog), encoding="utf-8")
    mapped = sum(len(a.get("kinetics_labels") or []) for a in catalog["actions"])
    print(f"catalog_version={catalog['catalog_version']}")
    print(f"actions={len(catalog['actions'])} mapped_kinetics_labels={mapped}")
    for p in (BACKEND_DATA, WORKER_DATA, MINI_DATA):
        print("wrote", p)


if __name__ == "__main__":
    main()
