"""Canonical 12-joint skeleton tensor used by training and inference."""

from __future__ import annotations

import math

import numpy as np


JOINT_NAMES = (
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
    "left_hip",
    "right_hip",
    "left_knee",
    "right_knee",
    "left_ankle",
    "right_ankle",
)
JOINT_INDEX = {name: index for index, name in enumerate(JOINT_NAMES)}
LABEL_SCHEMA_VERSION = "motion-semantic-v1"
MOVEMENT_LABELS = (
    "knee_dominant",
    "bilateral_lower_body",
    "unilateral_lower_body",
    "elbow_flexion_extension",
    "horizontal_upper_body",
    "static_or_low_amplitude",
)
REGION_LABELS = ("lower_body", "upper_body", "trunk_stability")


def _finite(value) -> bool:
    return type(value) in {int, float} and math.isfinite(value)


def _resample(sequence: np.ndarray, target_frames: int) -> np.ndarray:
    if len(sequence) == target_frames:
        return sequence.astype(np.float32, copy=False)
    if len(sequence) == 1:
        return np.repeat(sequence, target_frames, axis=0).astype(np.float32)
    source = np.linspace(0.0, 1.0, len(sequence))
    target = np.linspace(0.0, 1.0, target_frames)
    output = np.empty((target_frames, sequence.shape[1], sequence.shape[2]), dtype=np.float32)
    for joint in range(sequence.shape[1]):
        for channel in range(sequence.shape[2]):
            output[:, joint, channel] = np.interp(target, source, sequence[:, joint, channel])
    return output


def normalize_skeleton(sequence: np.ndarray) -> np.ndarray:
    if sequence.ndim != 3 or sequence.shape[1:] != (len(JOINT_NAMES), 3):
        raise ValueError("skeleton tensor must have shape [frames, 12, 3]")
    if not np.isfinite(sequence).all():
        raise ValueError("skeleton tensor contains non-finite values")
    output = sequence.astype(np.float32, copy=True)
    visibility = np.clip(output[:, :, 2], 0.0, 1.0)
    hips = (output[:, JOINT_INDEX["left_hip"], :2] + output[:, JOINT_INDEX["right_hip"], :2]) / 2
    shoulders = (
        output[:, JOINT_INDEX["left_shoulder"], :2]
        + output[:, JOINT_INDEX["right_shoulder"], :2]
    ) / 2
    torso = np.linalg.norm(shoulders - hips, axis=1)
    shoulder_width = np.linalg.norm(
        output[:, JOINT_INDEX["left_shoulder"], :2]
        - output[:, JOINT_INDEX["right_shoulder"], :2],
        axis=1,
    )
    scale = np.maximum(torso, shoulder_width)
    positive = scale[scale > 1e-5]
    fallback = float(np.median(positive)) if len(positive) else 1.0
    scale = np.where(scale > 1e-5, scale, fallback)
    output[:, :, :2] = (output[:, :, :2] - hips[:, None, :]) / scale[:, None, None]
    output[:, :, :2] *= (visibility >= 0.2)[:, :, None]
    output[:, :, 2] = visibility
    return output


def build_skeleton_tensor(samples: list[dict], target_frames: int = 64) -> np.ndarray:
    if not 8 <= target_frames <= 512:
        raise ValueError("target_frames must be between 8 and 512")
    frames = []
    for sample in samples:
        points = sample.get("skeleton") if isinstance(sample, dict) else None
        if not isinstance(points, list):
            continue
        frame = np.zeros((len(JOINT_NAMES), 3), dtype=np.float32)
        present = 0
        for point in points:
            if not isinstance(point, dict) or point.get("id") not in JOINT_INDEX:
                continue
            if not all(_finite(point.get(key)) for key in ("x", "y", "visibility")):
                continue
            frame[JOINT_INDEX[point["id"]]] = [
                float(point["x"]),
                float(point["y"]),
                float(point["visibility"]),
            ]
            present += 1
        if present >= 8:
            frames.append(frame)
    if len(frames) < 4:
        raise ValueError("at least four valid skeleton frames are required")
    return _resample(normalize_skeleton(np.stack(frames)), target_frames)


def load_pose_array(path, target_frames: int = 64) -> np.ndarray:
    """Load a local NPZ/NPY pose artifact generated by a licensed conversion step."""
    loaded = np.load(path, allow_pickle=False)
    if isinstance(loaded, np.lib.npyio.NpzFile):
        try:
            key = "skeleton" if "skeleton" in loaded.files else (
                "keypoints" if "keypoints" in loaded.files else None
            )
            if key is None:
                raise ValueError("pose NPZ must contain skeleton or keypoints")
            sequence = loaded[key]
        finally:
            loaded.close()
    else:
        sequence = loaded
    return _resample(normalize_skeleton(np.asarray(sequence)), target_frames)
