// AUTO-GENERATED by motion_catalog/generate.py from catalog.yaml.
// DO NOT EDIT BY HAND. Re-run: python motion_catalog/generate.py
const CATALOG_VERSION = "2026.09.30-02";
const CAPABILITY_PENDING_NOTE = "待 G 包验证后登记";
const ACTIONS = [
  {
    "id": "squat",
    "name_zh": "深蹲",
    "aliases": [
      "蹲起",
      "全蹲",
      "深蹲起"
    ],
    "kinetics_labels": [
      {
        "label": "squat",
        "class_index": 330
      }
    ],
    "kinetics_note": null,
    "visible_regions": [
      "hip",
      "knee",
      "ankle"
    ],
    "context_cues": [
      "knee_flexion",
      "trunk_upright",
      "depth_control"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": null,
      "quality_scorer": null
    },
    "knowledge_keys": [
      "squat_setup",
      "squat_depth",
      "squat_balance"
    ]
  },
  {
    "id": "pushup",
    "name_zh": "俯卧撑",
    "aliases": [
      "伏地挺身",
      "卧推撑"
    ],
    "kinetics_labels": [
      {
        "label": "push up",
        "class_index": 260
      }
    ],
    "kinetics_note": null,
    "visible_regions": [
      "shoulder",
      "elbow",
      "wrist"
    ],
    "context_cues": [
      "elbow_extension",
      "body_line",
      "trunk_brace"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": null,
      "quality_scorer": null
    },
    "knowledge_keys": [
      "pushup_setup",
      "pushup_elbow",
      "pushup_bodyline"
    ]
  },
  {
    "id": "lunge",
    "name_zh": "弓步蹲",
    "aliases": [
      "弓步",
      "箭步蹲",
      "前弓步"
    ],
    "kinetics_labels": [
      {
        "label": "lunge",
        "class_index": 183
      }
    ],
    "kinetics_note": null,
    "visible_regions": [
      "hip",
      "knee",
      "ankle"
    ],
    "context_cues": [
      "front_knee_flexion",
      "rear_hip_extension",
      "step_width"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": null,
      "quality_scorer": null
    },
    "knowledge_keys": [
      "lunge_setup",
      "lunge_depth",
      "lunge_stability"
    ]
  },
  {
    "id": "leg_abduction",
    "name_zh": "站姿腿外展",
    "aliases": [
      "腿外展",
      "侧抬腿",
      "髋外展"
    ],
    "kinetics_labels": [],
    "kinetics_note": "Kinetics-400 无腿外展精确标签；swinging legs/side kick 不等同，不强映射",
    "visible_regions": [
      "hip",
      "knee",
      "ankle"
    ],
    "context_cues": [
      "hip_abduction",
      "standing_balance",
      "controlled_return"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": null,
      "quality_scorer": null
    },
    "knowledge_keys": [
      "leg_abduction_setup",
      "leg_abduction_control"
    ]
  },
  {
    "id": "arm_abduction",
    "name_zh": "站姿臂外展",
    "aliases": [
      "臂外展",
      "侧平举站姿"
    ],
    "kinetics_labels": [],
    "kinetics_note": "Kinetics-400 无臂外展精确标签；front raises 属前平举，侧平举无对应类",
    "visible_regions": [
      "shoulder",
      "elbow",
      "wrist"
    ],
    "context_cues": [
      "shoulder_abduction",
      "elbow_straight",
      "controlled_return"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": null,
      "quality_scorer": null
    },
    "knowledge_keys": [
      "arm_abduction_setup",
      "arm_abduction_control"
    ]
  },
  {
    "id": "arm_vw",
    "name_zh": "手臂靠墙静力",
    "aliases": [
      "靠墙臂静力",
      "靠墙静蹲臂",
      "wall_static"
    ],
    "kinetics_labels": [],
    "kinetics_note": "靠墙静力为静态保持，Kinetics-400 无对应标签",
    "visible_regions": [
      "shoulder",
      "elbow",
      "trunk"
    ],
    "context_cues": [
      "wall_contact",
      "static_hold",
      "trunk_upright"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": null,
      "quality_scorer": null
    },
    "knowledge_keys": [
      "arm_vw_setup",
      "arm_vw_hold"
    ]
  },
  {
    "id": "bicep_curl",
    "name_zh": "哑铃弯举",
    "aliases": [
      "弯举",
      "肱二头肌弯举",
      "站姿弯举"
    ],
    "kinetics_labels": [],
    "kinetics_note": "Kinetics-400 无 bicep curls / 弯举类精确标签",
    "visible_regions": [
      "shoulder",
      "elbow",
      "wrist"
    ],
    "context_cues": [
      "handheld_weight",
      "elbow_flexion",
      "upper_arm_still"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": "hysteresis_cycle@v1",
      "quality_scorer": "rule_quality@v1"
    },
    "knowledge_keys": [
      "bicep_curl_setup",
      "bicep_curl_control"
    ]
  },
  {
    "id": "hammer_curl",
    "name_zh": "锤式弯举",
    "aliases": [
      "锤式弯举",
      "中立握弯举",
      "哑铃锤举"
    ],
    "kinetics_labels": [],
    "kinetics_note": "Kinetics-400 无锤式弯举精确标签",
    "visible_regions": [
      "shoulder",
      "elbow",
      "wrist"
    ],
    "context_cues": [
      "handheld_weight",
      "neutral_grip",
      "elbow_flexion"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": "hysteresis_cycle@v1",
      "quality_scorer": "rule_quality@v1"
    },
    "knowledge_keys": [
      "hammer_curl_setup",
      "hammer_curl_control"
    ]
  },
  {
    "id": "front_raise",
    "name_zh": "前平举",
    "aliases": [
      "前平举",
      "前抬臂",
      "哑铃前平举"
    ],
    "kinetics_labels": [
      {
        "label": "front raises",
        "class_index": 134
      }
    ],
    "kinetics_note": null,
    "visible_regions": [
      "shoulder",
      "elbow",
      "wrist"
    ],
    "context_cues": [
      "handheld_weight",
      "shoulder_flexion",
      "controlled_lower"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": "hysteresis_cycle@v1",
      "quality_scorer": "rule_quality@v1"
    },
    "knowledge_keys": [
      "front_raise_setup",
      "front_raise_control"
    ]
  },
  {
    "id": "lateral_raise",
    "name_zh": "侧平举",
    "aliases": [
      "侧平举",
      "侧抬臂",
      "哑铃侧平举"
    ],
    "kinetics_labels": [],
    "kinetics_note": "Kinetics-400 无 lateral raise / 侧平举精确标签",
    "visible_regions": [
      "shoulder",
      "elbow",
      "wrist"
    ],
    "context_cues": [
      "handheld_weight",
      "shoulder_abduction",
      "controlled_lower"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": "hysteresis_cycle@v1",
      "quality_scorer": "rule_quality@v1"
    },
    "knowledge_keys": [
      "lateral_raise_setup",
      "lateral_raise_control"
    ]
  },
  {
    "id": "shoulder_press",
    "name_zh": "肩推",
    "aliases": [
      "推举",
      "哑铃肩推",
      "坐姿肩推",
      "overhead_press"
    ],
    "kinetics_labels": [],
    "kinetics_note": "Kinetics-400 无 shoulder press / 肩推精确标签",
    "visible_regions": [
      "shoulder",
      "elbow",
      "wrist"
    ],
    "context_cues": [
      "handheld_weight",
      "shoulder_press",
      "trunk_brace"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": "hysteresis_cycle@v1",
      "quality_scorer": "rule_quality@v1"
    },
    "knowledge_keys": [
      "shoulder_press_setup",
      "shoulder_press_control"
    ]
  },
  {
    "id": "row",
    "name_zh": "划船",
    "aliases": [
      "俯身划船",
      "哑铃划船",
      "背划船",
      "bent_over_row"
    ],
    "kinetics_labels": [],
    "kinetics_note": "Kinetics-400 无划船 / rowing 精确标签",
    "visible_regions": [
      "shoulder",
      "elbow",
      "trunk"
    ],
    "context_cues": [
      "handheld_weight",
      "elbow_pull",
      "trunk_hinge"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": "hysteresis_cycle@v1",
      "quality_scorer": "rule_quality@v1"
    },
    "knowledge_keys": [
      "row_setup",
      "row_pull"
    ]
  },
  {
    "id": "deadlift",
    "name_zh": "硬拉",
    "aliases": [
      "硬拉",
      "罗马尼亚硬拉",
      "传统硬拉",
      "deadlift"
    ],
    "kinetics_labels": [
      {
        "label": "deadlifting",
        "class_index": 88
      }
    ],
    "kinetics_note": null,
    "visible_regions": [
      "hip",
      "knee",
      "shoulder"
    ],
    "context_cues": [
      "hip_hinge",
      "bar_path",
      "trunk_neutral"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": null,
      "quality_scorer": null
    },
    "knowledge_keys": [
      "deadlift_setup",
      "deadlift_hinge"
    ]
  },
  {
    "id": "bench_press",
    "name_zh": "卧推",
    "aliases": [
      "卧推",
      "杠铃卧推",
      "哑铃卧推",
      "bench_press"
    ],
    "kinetics_labels": [
      {
        "label": "bench pressing",
        "class_index": 19
      }
    ],
    "kinetics_note": null,
    "visible_regions": [
      "shoulder",
      "elbow",
      "wrist"
    ],
    "context_cues": [
      "supine",
      "hand_weight",
      "elbow_extension"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": null,
      "quality_scorer": null
    },
    "knowledge_keys": [
      "bench_press_setup",
      "bench_press_path"
    ]
  },
  {
    "id": "crunch",
    "name_zh": "卷腹",
    "aliases": [
      "卷腹",
      "仰卧卷腹",
      "腹卷"
    ],
    "kinetics_labels": [
      {
        "label": "situp",
        "class_index": 305
      }
    ],
    "kinetics_note": "现有 KINETICS_LABEL_ZH 将 situp 显示为卷腹；400 类无独立 crunch 标签",
    "visible_regions": [
      "trunk",
      "hip"
    ],
    "context_cues": [
      "supine",
      "trunk_flexion",
      "lower_back_contact"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": null,
      "quality_scorer": null
    },
    "knowledge_keys": [
      "crunch_setup",
      "crunch_flexion"
    ]
  },
  {
    "id": "plank",
    "name_zh": "平板支撑",
    "aliases": [
      "平板",
      "平板支撑",
      "直臂平板",
      "plank"
    ],
    "kinetics_labels": [],
    "kinetics_note": "Kinetics-400 无 planking / 平板支撑精确标签",
    "visible_regions": [
      "shoulder",
      "elbow",
      "trunk"
    ],
    "context_cues": [
      "prone",
      "body_line",
      "static_hold"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": "static_hold_timer@v1",
      "quality_scorer": "static_posture_quality@v1"
    },
    "knowledge_keys": [
      "plank_setup",
      "plank_hold"
    ]
  },
  {
    "id": "side_plank",
    "name_zh": "侧平板",
    "aliases": [
      "侧平板支撑",
      "侧桥",
      "side_plank"
    ],
    "kinetics_labels": [],
    "kinetics_note": "Kinetics-400 无侧平板精确标签",
    "visible_regions": [
      "shoulder",
      "trunk",
      "hip"
    ],
    "context_cues": [
      "side_lying",
      "body_line",
      "static_hold"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": "static_hold_timer@v1",
      "quality_scorer": "static_posture_quality@v1"
    },
    "knowledge_keys": [
      "side_plank_setup",
      "side_plank_hold"
    ]
  },
  {
    "id": "hip_bridge",
    "name_zh": "臀桥",
    "aliases": [
      "臀桥",
      "仰卧臀桥",
      "glute_bridge"
    ],
    "kinetics_labels": [],
    "kinetics_note": "Kinetics-400 无 hip bridge / 臀桥精确标签",
    "visible_regions": [
      "hip",
      "knee",
      "trunk"
    ],
    "context_cues": [
      "supine",
      "hip_extension",
      "heels_anchored"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": null,
      "quality_scorer": null
    },
    "knowledge_keys": [
      "hip_bridge_setup",
      "hip_bridge_lift"
    ]
  },
  {
    "id": "calf_raise",
    "name_zh": "提踵",
    "aliases": [
      "提踵",
      "踮脚",
      "站姿提踵",
      "calf_raise"
    ],
    "kinetics_labels": [],
    "kinetics_note": "Kinetics-400 无 calf raise / 提踵精确标签",
    "visible_regions": [
      "ankle",
      "knee"
    ],
    "context_cues": [
      "standing",
      "ankle_plantarflexion",
      "controlled_lower"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": null,
      "quality_scorer": null
    },
    "knowledge_keys": [
      "calf_raise_setup",
      "calf_raise_control"
    ]
  },
  {
    "id": "jumping_jack",
    "name_zh": "开合跳",
    "aliases": [
      "开合跳",
      "跳开合",
      "jumping_jack"
    ],
    "kinetics_labels": [],
    "kinetics_note": "Kinetics-400 无 jumping jack / 开合跳精确标签",
    "visible_regions": [
      "shoulder",
      "hip",
      "ankle"
    ],
    "context_cues": [
      "jump",
      "arm_abduction",
      "leg_abduction"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": null,
      "quality_scorer": null
    },
    "knowledge_keys": [
      "jumping_jack_setup",
      "jumping_jack_rhythm"
    ]
  },
  {
    "id": "mountain_climber",
    "name_zh": "登山跑",
    "aliases": [
      "登山跑",
      "俯身登山",
      "mountain_climber"
    ],
    "kinetics_labels": [],
    "kinetics_note": "Kinetics-400 无 mountain climber / 登山跑精确标签",
    "visible_regions": [
      "shoulder",
      "hip",
      "trunk"
    ],
    "context_cues": [
      "prone",
      "knee_drive",
      "core_brace"
    ],
    "capabilities": {
      "visual_recognition": true,
      "timeline": true,
      "technique_explanation": true,
      "repetition_counter": null,
      "quality_scorer": null
    },
    "knowledge_keys": [
      "mountain_climber_setup",
      "mountain_climber_rhythm"
    ]
  }
];
const KINETICS_TO_ID = {
  "squat": "squat",
  "push up": "pushup",
  "lunge": "lunge",
  "front raises": "front_raise",
  "deadlifting": "deadlift",
  "bench pressing": "bench_press",
  "situp": "crunch"
};
module.exports = { CATALOG_VERSION, CAPABILITY_PENDING_NOTE, ACTIONS, KINETICS_TO_ID };
