'use strict'

const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')

test('health capability center is discoverable, configurable and user-facing', () => {
  const app = JSON.parse(read('app.json'))
  const view = read('pages/settings/capabilities/index.wxml')
  const script = read('pages/settings/capabilities/index.js')

  assert.ok(app.pages.includes('pages/settings/capabilities/index'))
  assert.match(read('pages/settings/index.wxml'), /bindtap="capabilities"/)
  assert.match(read('pages/settings/index.js'), /pages\/settings\/capabilities\/index/)
  assert.match(view, /^<include src="\/components\/page-transition\/first-paint\.wxml"\/>\r?\n<page-transition\/>/)
  assert.match(view, /class="[^\"]*ui-page-content/)
  assert.match(script, /api\.get\('\/harness\/plugin-catalog'/)
  assert.match(script, /changeScope\(e\)/)
  assert.match(script, /changeChoice\(e\)/)
  assert.match(script, /healthmate_harness_pending:/)
  assert.match(script, /async function idempotentWrite/)
  assert.match(script, /'Idempotency-Key': pending\.key/)
  assert.match(view, /可以随时开启或关闭/)
  assert.doesNotMatch(view, /试运行预览|先预览再开启|合成示例/)
  assert.doesNotMatch(script, /async preview\(e\)/)
  assert.match(view, /允许提出行动申请/)
  assert.match(view, /查看使用记录/)
  assert.match(view, /删除能力配置/)
  assert.match(view, />关闭<\/button>/)
  assert.match(view, />开启<\/button>/)
  assert.match(view, /已关闭 · 历史记录保留/)
  assert.match(view, /一般健康参考，不替代医生诊断/)
  assert.doesNotMatch(view, /candidate_score|trace_id|模型名|tool_names/)
})

test('capability changes use direct enable and disable with explicit consent', () => {
  const script = read('pages/settings/capabilities/index.js')
  const view = read('pages/settings/capabilities/index.wxml')
  assert.match(script, /先关闭再调整/)
  assert.match(script, /关闭这项能力？/)
  assert.match(script, /'resume'/)
  assert.match(script, /'pause'/)
  assert.match(view, /开启这项能力/)
  assert.doesNotMatch(view, /previewed|disabled="\{\{!plugin\.previewed\}\}"/)
  assert.doesNotMatch(script, /plugin\.previewed|请先查看配置预览|重新预览后开启/)
  assert.match(script, /error\.code !== 'CAPABILITY_PREVIEW_REQUIRED'/)
  assert.match(script, /legacy-enable-bridge/)
  assert.match(view, /所有写入仍需你确认/)
  assert.match(script, /关闭后不再开展新的读取和建议/)
})
