'use strict'

const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')

test('health capability center is discoverable, configurable and user-facing', () => {
  const app = JSON.parse(read('app.json'))
  const view = read('pages/settings/capabilities/index.wxml')
  const script = read('pages/settings/capabilities/index.js')

  assert.ok(app.pages.includes('pages/settings/capabilities/index'))
  assert.match(read('pages/settings/index.wxml'), /bindtap="capabilities"/)
  assert.match(read('pages/settings/index.js'), /pages\/settings\/capabilities\/index/)
  assert.match(view, /^<include src="\/components\/page-transition\/first-paint\.wxml"\/>\r?\n<page-transition\/>/)
  assert.match(view, /class="[^\"]*ui-page-content/)
  assert.match(script, /api\.get\('\/harness\/plugin-catalog'/)
  assert.match(script, /changeScope\(e\)/)
  assert.match(script, /changeChoice\(e\)/)
  assert.match(script, /healthmate_harness_pending:/)
  assert.match(script, /async function idempotentWrite/)
  assert.match(script, /'Idempotency-Key': pending\.key/)
  assert.match(view, /试运行预览/)
  assert.match(view, /每项能力的目标与表达偏好只在对应场景生效/)
  assert.match(view, /合成示例 · 未读取你的个人数据/)
  assert.match(view, /允许提出行动申请/)
  assert.match(view, /查看使用记录/)
  assert.match(view, /删除能力配置/)
  assert.match(view, /暂停/)
  assert.match(view, /已暂停 · 历史记录保留/)
  assert.match(view, /一般健康参考，不替代医生诊断/)
  assert.doesNotMatch(view, /candidate_score|trace_id|模型名|tool_names/)
})

test('capability changes require preview, explicit consent and safe pause semantics', () => {
  const script = read('pages/settings/capabilities/index.js')
  const view = read('pages/settings/capabilities/index.wxml')
  assert.match(script, /先暂停再调整/)
  assert.match(script, /暂停这项能力？/)
  assert.match(script, /'preview'/)
  assert.match(script, /'resume'/)
  assert.match(script, /'pause'/)
  assert.match(view, /确认授权并开启/)
  assert.match(view, /所有写入仍需你确认/)
  assert.match(script, /暂停后不再开展新的读取和建议/)
})
