'use strict'
const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')

test('plan preview is fetched as a read-only draft and only applied after confirmation', () => {
  const js = read('pages/plan/index.js')
  const view = read('pages/plan/index.wxml')
  const floatView = read('components/agent-float/index.wxml')
  const floatScript = read('components/agent-float/index.js')
  assert.match(js, /\/agent\/runs\/\$\{runId\}/)
  assert.match(js, /detail\.plan_preview/)
  assert.match(view, /bindreviewconfirm="confirmPreview"/)
  assert.match(floatView, /bindtap="confirmPlanReview"/)
  assert.match(floatScript, /triggerEvent\('reviewconfirm'\)/)
  assert.match(js, /wx\.showModal\(/)
  assert.match(js, /result\.confirm/) 
  assert.match(js, /\/apply-plan/)
  assert.ok(js.indexOf('result.confirm') < js.indexOf('/apply-plan'), '写入调用必须位于明确确认之后')
  assert.match(js, /preview\.read_only === true/)
  assert.match(js, /write\.automatic === false/)
  assert.match(js, /this\._confirmPreviewOpen/)
})

test('plan preview becomes a text item inside the unified companion dialog', () => {
  const js = read('pages/plan/index.js')
  const view = read('pages/plan/index.wxml')
  const floatView = read('components/agent-float/index.wxml')

  assert.match(view, /<agent-float/)
  assert.match(view, /plan-review="\{\{floatingReview\}\}"/)
  assert.doesNotMatch(view, /agent-review-float|voice-only/)
  assert.match(floatView, /class="plan-review-text"/)
  assert.match(floatView, /\{\{message\.review\.content\}\}/)
  assert.match(floatView, /class="composer-voice tappable/)
  assert.match(js, /detail\.reply/)
  assert.match(js, /function displayTokens/)
  assert.match(js, /function formatPreviewMessage/)
  assert.match(js, /floatingReview:/)
})

test('unified plan dialog motion only transitions transform and opacity', () => {
  const style = read('components/agent-float/index.wxss')
  assert.match(style, /\.agent-dialog\{[^}]*opacity:0;transform:translateY\(24rpx\) scale\(\.98\)/)
  assert.match(style, /transition:opacity \.2s ease-out,transform \.3s/)
  assert.match(style, /@keyframes floatThinking/)
  assert.match(style, /@keyframes voiceRing/)
  assert.doesNotMatch(style, /transition[^;]*(?:color|font-size|font-weight|visibility)/)
})
